### PR TITLE
Configure for Travis, add build badge

### PR DESCRIPTION
**Pull request by robotnoises**
Just a basic Travis setup + build badge, per Issue [#56](https://github.com/firebase/angularfire-seed/issues/56).

Note: Someone with more firebase clout will need to update the build badge link in the Readme to point to the correct Travis account. Right now it's pointing to my forked repo.

### CODE REVIEW

**Comment by jwngr** [comment]
Thanks a ton for the PR @robotnoises! Kato and I are a bit swamped at the moment, but we will get around to this in due time. Just wanted to let you know that we appreciate the PR :bow:

**Comment by robotnoises** [comment]
You're very welcome. :smile:

**Comment by jwngr** [comment]
Thanks again @robotnoises! The badge looks beautiful :raised_hands:

**Comment by robotnoises** [comment]
She's a beaut!

**Pull request merged**
